### ISSUE TITLE
Failed Export Luna Classic to Terra wallet. Time out

### ISSUE THREAD

**Issue by d1gng** [Sifchain/Support-Tickets#433]
Hi i tried to move my 1.2m Luna tokens to my Terra wallet acc, but in this day IBC stopped working, so i received Failed, i didn't receive my Luna tokens Back to my Sifchian Adress. My sif Adress: sif1ttnemfwnwdexf98tk9rnlzuftwjgavu83gscfy

Useful link(2022-05-25): https://www.mintscan.io/sifchain/txs/F306E01BDE87C1E7882AF1B14FBDCC1F7BC2B8D6D1B2672436D951A7A7303A47

Please help me to receive my tokens back to Sifchain Wallet.

**Comment by emperorjm** [comment]
Hi @d1gng, the 1,418,777.020491 Unknown IBC tokens shown on your account are the same LUNAC tokens. If you hover over the token you will see that the same IBC denom is assigned (IBC/F141935FF02B74BDC6B8A0BD6FE86A23EE25D10E89AA0CD9158B3D92B63FDF4D) which is the same denom of the token that was transferred.

You can now try to transfer those tokens to Terra Classic.

**Comment by d1gng** [comment]
Hi sir, im talking not about 1,418,777 LUNC tokens, im asking about 1,239,502 tokens that failed here is the link on mintscan (https://www.mintscan.io/sifchain/txs/F306E01BDE87C1E7882AF1B14FBDCC1F7BC2B8D6D1B2672436D951A7A7303A47) 

TxHash
F306E01BDE87C1E7882AF1B14FBDCC1F7BC2B8D6D1B2672436D951A7A7303A47

This transaction was 3month ago (2022-05-17)

Here is my terra wallet address where I should receive my tokens, but if u check this address in  terra finder, all see that no transactions to this wallet. (link:  https://finder.terra.money/mainnet/address/terra1rwx4xr5yr9xchmnhgcrnchq7w2v6wqrjeeqkhs) 

So as operation has been expired (Timeout) I didn't receive my LUNA(LUNC) tokens in amount of  1,239,502 tokens, so they disappeared? I did unlock liquidity reset(I had 2.6 m tokens (1.4 m which you wrote about and 1.2m-which im talking about)), after I wanted to withdraw 1,2 million LUNA(LUNC) tokes to my terra wallet but I received nothing to my terra wallet and I did not received back tokens to my sifchain wallet.

**Comment by d1gng** [comment]
![image](https://user-images.githubusercontent.com/80422111/188491002-9ccc20a2-ca23-430d-ad78-791565da6d73.jpeg)![image](https://user-images.githubusercontent.com/80422111/188491018-0f7d8e8a-b6f8-4eda-8a6b-5e44c285499a.jpeg)

**Comment by d1gng** [comment]
Sir?

**Comment by emperorjm** [comment]
We are having this looked into further. Please note for Luna Classic you will need to use a blockexploerer like AtomScanhttps://atomscan.com/terra/accounts/terra1rwx4xr5yr9xchmnhgcrnchq7w2v6wqrjeeqkhs

**Comment by d1gng** [comment]
Hope everything gonna be solved with IBC, thanks for your time

**Comment by emperorjm** [comment]
@d1gng we have an external team hosting our Terra relayers and they are looking into this. I will let you know as soon as they find out what happened and what the solution is.

**Comment by d1gng** [comment]
i appreciate that!

**Comment by lufa23** [comment]
hey, can you confirm that the issue has been fixed?

**Comment by d1gng** [comment]
@lufa23 hi, no, I didn't receive my tokens to wallet.

**Comment by lufa23** [comment]
hey, just for you to know, we are working on it

**Comment by d1gng** [comment]
@lufa23 hi any updates about my situation? a lot of time passed

**Comment by lufa23** [comment]
hey, we have recently re-enabled the Terra Classic IBC client through the [governance proposal 120](https://wallet.keplr.app/chains/sifchain/proposals/120) (as it was expired). Can you confirm if the transaction went through?

**Comment by d1gng** [comment]
@lufa23 hi, unfortunately no tokens yet, seems ibc haven't send me Lona tokens

**Comment by greg-szabo** [comment]
Here's a summary I wrote up about the investigation:

The user is claiming 1239502 LUNA/LUNC token is missing from his/her account. Mintscan shows a transaction that sent this amount over to Terra (Classic) at height `6879637`.

In the user wallet balance, the tokens are last seen at height `6879632`, 5 blocks before the transaction was included in block `6879637`
```
❯ sifnoded q bank balances sif1ttnemfwnwdexf98tk9rnlzuftwjgavu83gscfy --height 6879632
balances:
- amount: "10677255507677346"
  denom: ceth
- amount: "1239502221471"
  denom: ibc/F141935FF02B74BDC6B8A0BD6FE86A23EE25D10E89AA0CD9158B3D92B63FDF4D
- amount: "1978486779492301878"
  denom: rowan
```
Based on the claimed account, we are looking at the IBC-denominated token with denom `ibc/F141935FF02B74BDC6B8A0BD6FE86A23EE25D10E89AA0CD9158B3D92B63FDF4D`.

After block `6879632` the tokens do not show at the user balance and all subsequent blocks show the below balance.
```
❯ sifnoded q bank balances sif1ttnemfwnwdexf98tk9rnlzuftwjgavu83gscfy --height 6879637
balances:
- amount: "10677255507677346"
  denom: ceth
- amount: "1478486779492301878"
  denom: rowan
```

---

Then at height `6990179`, when the timeout happens, the tokens show up again in the user's wallet as expected. Note that the tokens weren't available at the previous height and the timeout message made them available again at the correct height.

```
❯ sifnoded q bank balances sif1ttnemfwnwdexf98tk9rnlzuftwjgavu83gscfy --height 6990178
balances:
- amount: "10677255507677346"
  denom: ceth
- amount: "1478486779492301878"
  denom: rowan

❯ sifnoded q bank balances sif1ttnemfwnwdexf98tk9rnlzuftwjgavu83gscfy --height 6990179
balances:
- amount: "10677255507677346"
  denom: ceth
- amount: "1239502221471"
  denom: ibc/F141935FF02B74BDC6B8A0BD6FE86A23EE25D10E89AA0CD9158B3D92B63FDF4D
- amount: "1478486779492301878"
  denom: rowan
```

Also note that the IBC team at Informal Systems went through the SDK code and the block data too and confirmed that all events that are related to this IBC transaction are triggered properly and show up in the blocks.

As far as we see, this IBC transaction worked in line with the protocol design.

I quickly checked later movements on the wallet and the next time those tokens were touched was two months ago, at height `8100476` in this transaction: https://www.mintscan.io/sifchain/txs/C9726673B3213B78A6E4AC17415038AAF18B8BBDCDABB659696C35AE0697B840

The wallet since has been drained of the token and current balance does not show any.

It is possible that the type of wallet UI the user used did not show the tokens for some reason but that is beyond the IBC protocol's reach.

IBC does not "send" tokens back to the owner if a transaction fails. The TimeOut message releases the tokens back into the owner's wallet. Hence, there is no "Send" transaction when tokens are returned. Only the "TimeOut" transaction. In this case, the TimeOut transaction worked as intented both by multiple teams.

The next transaction at height `8100476` is an UnlockLiquidityRequest which is a bit strange to me. There could have been a transaction making all the tokens illiquid but in my cursory search, I didn't find that. The tokens showed up in the wallet in the sampled blocks between the TimeOut message and the UnlockLiquidityRequest message so it's hard to think of them as illiquid tokens. I wonder if they were illiquid in the first place and the original Send message was not supposed to go through? These are just speculations at this point, but all in all, the tokens were there up until two months ago.
